name: hugo
version: "0.50-DEV"
summary: Fast and Flexible Static Site Generator
description: |
  Hugo is a static HTML and CSS website generator written in Go. It is
  optimized for speed, easy use and configurability. Hugo takes a directory
  with content and templates and renders them into a full HTML website.
confinement: strict
grade: devel # "devel" or "stable"
environment:
    GO111MODULE: on

apps:
  hugo:
    command: bin/hugo
    completer: hugo-completion
    plugs: [home, network-bind, removable-media]

parts:
  hugo:
    source: .
    plugin: go
    go-importpath: github.com/gohugoio/hugo
    build-packages:
      - git
    override-build: |
      echo "\nStarting override-build:"
      export GOPATH=$(dirname $SNAPCRAFT_PART_INSTALL)/go
      export PATH=$GOPATH/bin:$PATH
      cd $GOPATH/src/github.com/gohugoio/hugo
      echo ' * Running "go get -v github.com/magefile/mage"...'
      go get -v github.com/magefile/mage
      echo ' * Running "mage -v test"...'
      mage -v test
      echo " * Building hugo (build tag: none)..."
      [ "$SNAPCRAFT_PROJECT_GRADE" = "stable" ] && mage -v hugoNoGitInfo || mage -v hugo
      ./hugo version
      ldd hugo || :
      echo " * Building shell completion..."
      ./hugo gen autocomplete --completionfile=hugo-completion
      echo " * Installing to ${SNAPCRAFT_PART_INSTALL}..."
      install -d $SNAPCRAFT_PART_INSTALL/bin
      cp -av hugo $SNAPCRAFT_PART_INSTALL/bin/
      mv -v hugo-completion $SNAPCRAFT_PART_INSTALL/
      echo " * Stripping binary..."
      ls -l $SNAPCRAFT_PART_INSTALL/bin/hugo
      strip --remove-section=.comment --remove-section=.note $SNAPCRAFT_PART_INSTALL/bin/hugo
      ls -l $SNAPCRAFT_PART_INSTALL/bin/hugo
    after: [go]

  go:
    source-tag: go1.11

  git:
    plugin: nil
    stage-packages: [git]
    prime: [usr/bin/git]

  node:
    plugin: nodejs
    prime:
      - bin/node

  pygments:
    plugin: python
    python-packages: [Pygments]
    prime:
      - bin/pygmentize
      - lib/python*/site-packages/Pygments-*.dist-info/*
      - lib/python*/site-packages/pygments/*
      - usr/bin/python*
      - -usr/bin/python*m
      - usr/lib/python*/*
      - -usr/lib/python*/distutils/*
      - -usr/lib/python*/email/*
      - -usr/lib/python*/lib2to3/*
      - -usr/lib/python*/tkinter/*
      - -usr/lib/python*/unittest/*
