name: hugo
version: "0.31.1"
summary: Fast and Flexible Static Site Generator
description: |
  Hugo is a static HTML and CSS website generator written in Go. It is
  optimized for speed, easy use and configurability. Hugo takes a directory
  with content and templates and renders them into a full HTML website.
confinement: strict
grade: stable # "devel" or "stable"

apps:
  hugo:
    command: bin/hugo
    plugs: [home, network-bind]

parts:
  hugo:
    source: .
    plugin: go
    go-importpath: github.com/gohugoio/hugo
    build-packages:
      - git
      - make
    stage-packages:
      - git
      - python-pygments
    prepare: |
      export GOPATH=$(dirname $SNAPCRAFT_PART_INSTALL)/go
      export PATH=$GOPATH/bin:$PATH
      cd $GOPATH/src/github.com/gohugoio/hugo
      go get github.com/magefile/mage
      mage vendor
      mage test
      rm -f $GOPATH/bin/dep
      rm -f $GOPATH/bin/mage
    install: |
      strip --remove-section=.comment --remove-section=.note $SNAPCRAFT_PART_INSTALL/bin/hugo
    after: [go]
  go:
    source-tag: go1.9.2
