name: "Check spelling"
on:
  push:
  pull_request:
    branches-ignore:
      - "dependabot/**"

permissions:
  contents: read

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: streetsidesoftware/cspell-action@v7
        with:
          incremental_files_only: true
          strict: true
          # cspell uses the .cspell.json configuration file
      - uses: codespell-project/actions-codespell@v2
        with:
          check_filenames: true
          check_hidden: true
          # codespell uses the .codespellrc file
