// Code generated by "stringer -type=PathType"; DO NOT EDIT.

package paths

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PathTypeFile-0]
	_ = x[PathTypeContentResource-1]
	_ = x[PathTypeContentSingle-2]
	_ = x[PathTypeLeaf-3]
	_ = x[PathTypeBranch-4]
}

const _PathType_name = "PathTypeFilePathTypeContentResourcePathTypeContentSinglePathTypeLeafPathTypeBranch"

var _PathType_index = [...]uint8{0, 12, 35, 56, 68, 82}

func (i PathType) String() string {
	if i < 0 || i >= PathType(len(_PathType_index)-1) {
		return "PathType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PathType_name[_PathType_index[i]:_PathType_index[i+1]]
}
