// Code generated by "stringer -type Type"; DO NOT EDIT.

package paths

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeFile-0]
	_ = x[TypeContentResource-1]
	_ = x[TypeContentSingle-2]
	_ = x[TypeLeaf-3]
	_ = x[TypeBranch-4]
	_ = x[TypeContentData-5]
	_ = x[TypeMarkup-6]
	_ = x[TypeShortcode-7]
	_ = x[TypePartial-8]
	_ = x[TypeBaseof-9]
}

const _Type_name = "TypeFileTypeContentResourceTypeContentSingleTypeLeafTypeBranchTypeContentDataTypeMarkupTypeShortcodeTypePartialTypeBaseof"

var _Type_index = [...]uint8{0, 8, 27, 44, 52, 62, 77, 87, 100, 111, 121}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
